CREATE OR REPLACE DATABASE SNOWFLAKEDB;

CREATE OR REPLACE SCHEMA SPOTIFY_DATA;

CREATE OR REPLACE TABLE TBL_ALBUM (
    ALBUM_ID VARCHAR(200) PRIMARY KEY,
    NAME VARCHAR(200),
    RELEASE_DATE DATE,
    TOTAL_TRACKS INT,
    URL VARCHAR(500)
);

CREATE OR REPLACE TABLE TBL_ARTIST (
    ARTIST_ID VARCHAR(200) PRIMARY KEY,
    ARTIST_NAME VARCHAR(200),
    EXTERNAL_URL VARCHAR(500)
);

CREATE OR REPLACE TABLE TBL_SONGS (
    SONG_ID VARCHAR(200) PRIMARY KEY,
    SONG_NAME VARCHAR(200),
    DURATION_MS INT,
    URL VARCHAR(500),
    POPULARITY INT,
    SONG_ADDED DATETIME,
    ALBUM_ID VARCHAR(200),
    ARTIST_ID VARCHAR(200)
);

CREATE OR REPLACE STORAGE INTEGRATION s3_init
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::<your-aws-account-id>:role/<your-role-name>'
    ENABLED = TRUE
    STORAGE_ALLOWED_LOCATIONS = ('s3://spotify-etl-pipeline-sumanth-dec25/transformed_data/');

DESC INTEGRATION s3_init;

CREATE OR REPLACE FILE FORMAT parquet_fileformat
    TYPE = 'PARQUET';

CREATE OR REPLACE STAGE spotify_stage
    URL = 's3://spotify-etl-pipeline-sumanth-dec25/transformed_data/'
    STORAGE_INTEGRATION = s3_init
    FILE_FORMAT = parquet_fileformat;

LIST @spotify_stage/album_data/;
LIST @spotify_stage/artist_data/;
LIST @spotify_stage/songs_data/;

COPY INTO SNOWFLAKEDB.SPOTIFY_DATA.TBL_ALBUM
FROM @spotify_stage/album_data/
FILE_FORMAT = parquet_fileformat
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO SNOWFLAKEDB.SPOTIFY_DATA.TBL_ARTIST
FROM @spotify_stage/artist_data/
FILE_FORMAT = parquet_fileformat
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO SNOWFLAKEDB.SPOTIFY_DATA.TBL_SONGS
FROM @spotify_stage/songs_data/
FILE_FORMAT = parquet_fileformat
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

SELECT COUNT(*) AS album_count FROM SNOWFLAKEDB.SPOTIFY_DATA.TBL_ALBUM;
SELECT COUNT(*) AS artist_count FROM SNOWFLAKEDB.SPOTIFY_DATA.TBL_ARTIST;
SELECT COUNT(*) AS songs_count FROM SNOWFLAKEDB.SPOTIFY_DATA.TBL_SONGS;

CREATE OR REPLACE PIPE SNOWFLAKEDB.SPOTIFY_DATA.TBL_ALBUM_PIPE
    AUTO_INGEST = TRUE
AS
    COPY INTO SNOWFLAKEDB.SPOTIFY_DATA.TBL_ALBUM
    FROM @spotify_stage/album_data/
    FILE_FORMAT = parquet_fileformat
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

CREATE OR REPLACE PIPE SNOWFLAKEDB.SPOTIFY_DATA.TBL_ARTIST_PIPE
    AUTO_INGEST = TRUE
AS
    COPY INTO SNOWFLAKEDB.SPOTIFY_DATA.TBL_ARTIST
    FROM @spotify_stage/artist_data/
    FILE_FORMAT = parquet_fileformat
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

CREATE OR REPLACE PIPE SNOWFLAKEDB.SPOTIFY_DATA.TBL_SONGS_PIPE
    AUTO_INGEST = TRUE
AS
    COPY INTO SNOWFLAKEDB.SPOTIFY_DATA.TBL_SONGS
    FROM @spotify_stage/songs_data/
    FILE_FORMAT = parquet_fileformat
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

DESC PIPE SNOWFLAKEDB.SPOTIFY_DATA.TBL_ALBUM_PIPE;
DESC PIPE SNOWFLAKEDB.SPOTIFY_DATA.TBL_ARTIST_PIPE;
DESC PIPE SNOWFLAKEDB.SPOTIFY_DATA.TBL_SONGS_PIPE;

SELECT SYSTEM$PIPE_STATUS('SNOWFLAKEDB.SPOTIFY_DATA.TBL_ALBUM_PIPE');
SELECT SYSTEM$PIPE_STATUS('SNOWFLAKEDB.SPOTIFY_DATA.TBL_ARTIST_PIPE');
SELECT SYSTEM$PIPE_STATUS('SNOWFLAKEDB.SPOTIFY_DATA.TBL_SONGS_PIPE');

